"""event_start

Revision ID: 32cdfa2a62a8
Revises: 1b3a9596e713
Create Date: 2024-03-28 16:48:00.261938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32cdfa2a62a8'
down_revision: Union[str, None] = '1b3a9596e713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_start', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('event_end', sa.DateTime(), nullable=True))
    op.drop_column('event', 'date')
    op.drop_column('event', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event', 'event_end')
    op.drop_column('event', 'event_start')
    # ### end Alembic commands ###
