"""tick_link2

Revision ID: 78855b2c2dc5
Revises: effe4d06cdff
Create Date: 2024-04-03 19:17:00.707521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78855b2c2dc5'
down_revision: Union[str, None] = 'effe4d06cdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'link', new_column_name='ticket_link', existing_type=sa.String())
    # ### end Alembic commands ###ds ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'ticket_link', new_column_name='link', existing_type=sa.String())
    # ### end Alembic commands ###