"""cascade2

Revision ID: 82258500f90b
Revises: 4c16f3adc683
Create Date: 2024-03-28 17:46:00.090726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82258500f90b'
down_revision: Union[str, None] = '4c16f3adc683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('save_user_id_fkey', 'save', type_='foreignkey')
    op.drop_constraint('save_event_id_fkey', 'save', type_='foreignkey')
    op.create_foreign_key(None, 'save', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'save', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'save', type_='foreignkey')
    op.drop_constraint(None, 'save', type_='foreignkey')
    op.create_foreign_key('save_event_id_fkey', 'save', 'event', ['event_id'], ['id'])
    op.create_foreign_key('save_user_id_fkey', 'save', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
