"""init

Revision ID: a39db9c2fc3b
Revises: 
Create Date: 2024-03-29 10:29:14.574130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39db9c2fc3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('time', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('event_img', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name_first', sa.String(), nullable=True),
    sa.Column('name_last', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('save',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('event')
    # ### end Alembic commands ###
