"""Initial migration

Revision ID: f747a99c97be
Revises: ce542021a080
Create Date: 2024-03-28 12:23:26.546561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f747a99c97be'
down_revision: Union[str, None] = 'ce542021a080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'save', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'save', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'save', type_='foreignkey')
    op.drop_constraint(None, 'save', type_='foreignkey')
    # ### end Alembic commands ###
